### ISSUE TITLE
H9- Eu como usuário quero poder filtrar por gastos pagos e não pagos

### ISSUE THREAD

**Issue by matosGu1lherme** [Fgarm/GUMA-investimentos#10]
##### Front
- [x]  Inserir campo para selecionar gastos pagos e não pagos no Front-end
- [x] Enviar dados para API do Back-end

##### Back
- Para receber dados do Front-end
  - [x] criar URL para filtro por gasto pago ou não pago
  - [x] criar método na Views de gastos que fará a consulta no BD para obter os gastos que foram pagos ou não

**Comment by Fgarm** [comment]
Done
