### ISSUE TITLE
H14 - Eu como usuario quero ver minha média mensal de gastos por tipo de gastos

### ISSUE THREAD

**Issue by matosGu1lherme** [Fgarm/GUMA-investimentos#11]
- [ ] Reunir dados na api por tipo de tag
- [ ] fazer media dos gastos por tag
- [ ] enviar dados para frontend
- [ ] receber dados backend
- [ ] mostrar dados de forma ilustrativa(grafico?)

**Comment by GustavoMartinx** [comment]
duplicada
