### ISSUE TITLE
H13 - Eu como usuário quero cadastrar um saldo

### ISSUE THREAD

**Issue by matosGu1lherme** [Fgarm/GUMA-investimentos#12]
- [x] Maneira de armazenar transações recorrentes no backend sem sobrescrever as antigas
- [x] Área no Front-end para mostrar variações de saldos
- [x] Enviar dados para Front-end
- [x] Receber dados no Front-end
- [x] Mostrar dados de forma iterativa (gráfico?)

**Comment by Fgarm** [comment]
Closed by  #45
