### ISSUE TITLE
H1 - Eu como usuário quero ser capaz de cadastrar uma conta para armazenar meus dados pessoais

### ISSUE THREAD

**Issue by matosGu1lherme** [Fgarm/GUMA-investimentos#5]
- [x] Conectar com SGBD 
- [x]  Criar uma tabela banco de dados através Django framework para cadastrar os dados de um usuario 
- [x]  Enviar dados por rota para backend
- [x]  Criar um front end de cadastro com os campos (nome, sobrenome, e-mail, senha)
- [x]  armazenar banco de dados informações recebidas pelo formulario frontend

**Comment by matosGu1lherme** [comment]
- Estou fazendo as tarefas de criar tabela de usuário
- conectar Sgbd 
- cadastrar dados sgbd
- criar rota

**Comment by thiagogquinto** [comment]
Estou fazendo a tarefa de front-end de cadastro e envio de dados para backend

**Comment by Fgarm** [comment]
Done
