### ISSUE TITLE
H10 - Eu como usuário quero poder ver meu extrato de entradas e saídas

### ISSUE THREAD

**Issue by GustavoMartinx** [Fgarm/GUMA-investimentos#51]
## Front-End
- [x] ordenar gastos por data
- [x] adicionar parte de adicionar entradas no Home
- [x] organizar disposição das informações dos gasto/entradas

## Back-End
- [x]  função de cadastrar entradas
- [x]  função para recuperar entradas 

## Obs:

- As partes de gráficos adicionadas pelo Gustavo já estão "mergeadas" nessa branch

## Pontos a ver:
-  *Disposição das informações*: como as entradas não possui as mesmas informações de gastos a disposição fica igual
- A cor de fundo para as infos de gastos/entradas é só um teste
- Aparentemente aquele erro dos gráficos foi só um acaso, pois criei um novo usuário e aparentemente funcionou

**Comment by matosGu1lherme** [comment]
Atualização do BackEnd para mandar dados de forma sequencial e juntanto gastos, a saldos
