### ISSUE TITLE
H6- Eu como usuário quero poder colocar tags em gastos

### ISSUE THREAD

**Issue by matosGu1lherme** [Fgarm/GUMA-investimentos#7]
- [x] Criar area de tags na tabela de gastos 
- [x] Criar uma tabela de tags
- [x] Criar relação entre tabela de gastos e tabela de tags
- [x] modificar front gastos para receber tag

**Comment by Fgarm** [comment]
Vou pegar a tarefas:
- Criar uma tabela de tags

**Comment by Fgarm** [comment]
Done
