### ISSUE TITLE
H7 - Eu como usuário quero poder filtrar gastos por tags

### ISSUE THREAD

**Issue by matosGu1lherme** [Fgarm/GUMA-investimentos#8]
- [x] Inserir campo para selecionar tag no Front-end
- [x] Enviar requisição para API do Back-end
- [x] Criar querry a ser feita no BD para obter os gastos que têm a tag desejada

**Comment by Fgarm** [comment]
- [x] Criar querry a ser feita no BD para obter os gastos que têm a tag desejada
Vou pegar essa tarefa

**Comment by Fgarm** [comment]
Done
